spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/wheel}
    username: ${DATABASE_USERNAME:wheel}
    password: ${DATABASE_PASSWORD:wheel}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: ${PORT:8080}
  error:
    include-stacktrace: never
    include-exception: false
